version: '3.9'

services:
  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mikro_db


  cashe:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'