version: '3.9'

services:
  db-test:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mikro_db-test


  cache-test:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'

  rabbitmq-test:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'