name : CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run:
        |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: black
      run: poetry run black up
    - name: ruff
      run: poetry run ruff check app

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run:
          |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: run unit test
        run: poetry run pytest tests/unit


      

